
[general]
import = [
  "~/.config/alacritty/color-theme-catppucchin-macchiato.toml"
]


[env]
TERM = "xterm-256color"


[font]
size = 13.0

[font.normal]
family = "IosevkaTerm Nerd Font Mono"
style = "Regular"

[font.bold]
family = "IosevkaTerm Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "IosevkaTerm Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "IosevkaTerm Nerd Font Mono"
style = "Italic"
